#pragma once

#include "ControlNode.hpp"
#include "sootc/node/Node.hpp"
#include <memory>
#include <optional>
#include <string>

namespace sootc {

    // (while test [:label <symbol>] body...)
    //
    // Semantics:
    //   * test is evaluated before each iteration; when it yields false,
    //     control transfers to the instruction after the loop.
    //   * body is a single ExpressionNode emitted once per iteration.
    //   * :label, when present, names the loop in FunctionNode::m_labels.
    //     Without :label the loop is assigned a compiler-generated name
    //     of the form "while_start_N" / "while_end_N". With :label the
    //     user-supplied symbol is used as-is for the entry label, and
    //     "<symbol>_end" is used for the exit label.
    //
    // The label is currently informational: there is no break/continue
    // form that could reference it from inside the body. It is, however,
    // stable across compilations of the same source, which makes it useful
    // for disassembly and for future extensions.
    class WhileNode : public ControlNode {
        std::unique_ptr<ExpressionNode> m_condition;
        std::unique_ptr<ExpressionNode> m_body;

        // Optional user-supplied loop label. When set, the loop's entry
        // label in FunctionNode::m_labels is exactly this name, and the
        // exit label is "<name>_end". When unset, both labels are
        // generated by FunctionNode::create_unique_label.
        std::optional<std::string> m_label;

    public:
        WhileNode(std::unique_ptr<ExpressionNode> cond, std::unique_ptr<ExpressionNode> body)
            : ControlNode(NodeType::WhileNode), m_condition(std::move(cond)),
              m_body(std::move(body)) {}

        // Set the user-supplied loop label. Called by NodeBuilder when it
        // parses a :label keyword in the while form.
        void set_label(std::string name) { m_label = std::move(name); }

        // Read accessors used by NodeBuilder and by to_string.
        const std::optional<std::string> &label() const { return m_label; }

     void emit(FunctionNode &fn) override {
            // Choose the entry and exit label names. With a user-supplied
            // label the entry is exactly that name and the exit is
            // "<name>_end". Without one, both are compiler-generated so
            // that they cannot collide across nested loops in the same
            // function.
            std::string start_label;
            std::string end_label;

            if (m_label.has_value() && !m_label->empty()) {
                start_label = *m_label;
                end_label = start_label + "_end";
            } else {
                start_label = fn.create_unique_label("while_start");
                end_label = fn.create_unique_label("while_end");
            }

            // Emit the loop.
            //
            //   start_label:
            //     <evaluate test into cond_reg>
            //     BranchIfNot cond_reg, end_label
            //     <body>
            //     Branch start_label
            //   end_label:
            fn.add_label(start_label);

            m_condition->emit(fn);
            u8 cond_reg = fn.get_temp_reg(m_condition.get());

            fn.add_instruction(Opcode::BranchIfNot, cond_reg, 0, 0);
            fn.add_branch_reference(end_label);

            m_body->emit(fn);

            fn.add_instruction(Opcode::Branch, 0, 0, 0);
            fn.add_branch_reference(start_label);

            fn.add_label(end_label);

            // Register a result register for this node.
            //
            // WhileNode has no meaningful value of its own: the loop is
            // executed for its side effects and the result is unspecified.
            // However, the compiler requires every ExpressionNode that is
            // used as the last expression of a sequence or as the value of
            // a `let` to have a temp register assigned, otherwise
            // SequenceNode::emit / LetNode::emit will fail with
            // "get_temp_reg: node ... has no temp reg".
            //
            // We reuse the register that held the (now dead) condition, so
            // no extra register is consumed. If for some reason the
            // condition did not allocate a register, fall back to r0.
            const u8 result_reg = fn.has_temp_reg(m_condition.get())
                                      ? fn.get_temp_reg(m_condition.get())
                                      : static_cast<u8>(0);
            fn.set_temp_reg(this, result_reg);
        }

        std::string to_string() const override {
            std::string result = "(while " + m_condition->to_string();
            if (m_label.has_value() && !m_label->empty()) { result += " :label " + *m_label; }
            result += " " + m_body->to_string() + ")";
            return result;
        }
    };

} // namespace sootc