(
  (define (add-func x y)
    (let result)
	(add result x y)
	(ret result)
  )
  (define (test)
    (let result func funcn)
	(lookp func add-func)
	(ldsi 24 100)
	(ldsi 25 100)
	(call func result 2)
	(lookp funcn print)
	(move 24 result)
	(calln funcn result 1)
	(ret 0)
  )
)